from flask import Blueprint, jsonify, request

question_bp = Blueprint('question', __name__, url_prefix='/question')

@question_bp.route('/1/', methods=['GET', 'POST'])
def q1():
    dict = {
            'qnum' :    '1',
            'qtext':    'What is the sum of game.data(1) and 3154?',
            'qdata':    5927,
            'qans' :    '9081'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qtext': dict['qtext'], 'qnum': dict['qnum'], 'qdata': dict['qdata']})

@question_bp.route('/2/', methods=['GET', 'POST'])
def q2():
    dict = {
            'qnum'  :   '2',
            'qtext' :   'What is the length of the string returned by game.data(2)?',
            'qdata' :   'You bring the crowns and heads of conquered kings to my city steps! You insult my queen, You threaten my people with slavery and death. Oh Ive chosen my words carefully persian, perhaps you should have done the same.',
            'qans'  :   '216'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/3/', methods=['GET', 'POST'])
def q3():
    dict = {
            'qnum'  :   '3',
            'qtext' :   'Which element in the list returned by game.data(3) is at index position 38?',
            'qdata' :   [386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 958, 743, 527],
            'qans'  :   '892'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/4/', methods=['GET', 'POST'])
def q4():
    dict = {
            'qnum'  :   '4',
            'qtext' :   'Return a string that contains the characters starting from index 10 and going upto but not including the character at index 25 in the string generated by the game.data(4) method.',
            'qdata' :   'Yes! Yes! Bombay is berry berry nice this time of the year.',
            'qans'  :   'Bombay is berry'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/5/', methods=['GET', 'POST'])
def q5():
    dict = {
            'qnum'  :   '5',
            'qtext' :   'Reverse the string generated by game.data(5) function.',
            'qdata' :   'Yes! Yes! Bombay is berry berry nice this time of the year.',
            'qans'  :   '.raey eht fo emit siht ecin yrreb yrreb si yabmoB !seY !seY'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/6/', methods=['GET', 'POST'])
def q6():
    dict = {
            'qnum'  :   '6',
            'qtext' :   'Reverse the second half of the string in game.data(6) and then return the complete string so that the first half of the answer is unchanged and the second half is reversed.',
            'qdata' :   'You think darkness is your ally. But you merely adopted the dark. I was born in it, moulded by it.',
            'qans'  :   'You think darkness is your ally. But you merely ad.ti yb dedluom ,ti ni nrob saw I .krad eht detpo'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/7/', methods=['GET', 'POST'])
def q7():
    dict = {
            'qnum'  :   '7',
            'qtext' :   'Create a string by joining all the elements in the list returned by game.data(7) seperated by a space',
            'qdata' :   ['Badges!','We','dont','need','no','stinkin','badges.'],
            'qans'  :   'Badges! We dont need no stinkin badges.'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/8/', methods=['GET', 'POST'])
def q8():
    dict = {
            'qnum'  :   '8',
            'qtext' :   'Increment each element in the list returned by game.data(8) method by 15',
            'qdata' :   [386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 958, 743, 527],
            'qans'  :   '[401, 477, 62, 433, 922, 359, 251, 390, 838, 581, 612, 993, 343, 630, 968, 360, 414, 177, 773, 234, 933, 252, 427, 581, 841, 263, 881, 965, 641, 964, 702, 232, 830, 82, 119, 73, 527, 39, 907, 909, 782, 568, 96, 394, 858, 846, 460, 757, 732, 973, 758, 542]'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/9/', methods=['GET', 'POST'])
def q9():
    dict = {
            'qnum'  :   '9',
            'qtext' :   'The method game.data(9) returns a nested list that further contains 2 lists. Add each element of the first inner list with each element at the same index in the second inner list and return the answer as a new list',
            'qdata' :   [[456, 39, 532, 126, 245, 57, 27], [91, 234, 43, 438, 317, 619, 30]],
            'qans'  :   '[547, 273, 575, 564, 562, 676, 57]'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/10/', methods=['GET', 'POST'])
def q10():
    dict = {
            'qnum'  :   '10',
            'qtext' :   'The method game.data(10) returns a list where each element is the hexadecimal representation of a unicode character. Convert all the characters, join them & submit your answer as a string.',
            'qdata' :   ['0x54', '0x68', '0x65', '0x72', '0x65', '0x73', '0x20', '0x61', '0x20', '0x50', '0x68', '0x6f', '0x65', '0x62', '0x65', '0x20', '0x6f', '0x6e', '0x20', '0x6d', '0x79', '0x20', '0x73', '0x61', '0x6e', '0x64', '0x77', '0x69', '0x63', '0x68', '0x21'],
            'qans'  :   'Theres a Phoebe on my sandwich!'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/11/', methods=['GET', 'POST'])
def q11():
    dict = {
            'qnum'  :   '11',
            'qtext' :   'The method game.data(11) returns a base64 encoded string. Decode and return this string',
            'qdata' :   'RmFpdGggaW4geW91ciBuZXcgYXBwcmVudGljZSwgbWlzcGxhY2VkIG1heSBiZS4gQXMgaXMgeW91ciBmYWl0aCBpbiB0aGUgZGFyayBzaWRlIG9mIHRoZSBmb3JjZS4gQXQgYW4gZW5kIHlvdXIgcnVsZSBpcy4gQW5kIHNob3J0IGVub3VnaCBpdCB3YXMh',
            'qans'  :   'Faith in your new apprentice, misplaced may be. As is your faith in the dark side of the force. At an end your rule is. And short enough it was!'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/12/', methods=['GET', 'POST'])
def q12():
    dict = {
            'qnum'  :   '12',
            'qtext' :   'Count the number of occurences of the word "the" in the string returned by game.data(12)',
            'qdata' :   'Out of the night that covers me, Black as the pit from pole to pole. I thank whatever gods may be, For my unconquerable soul. In the fell clutch of circumstance, I have not winced nor cried aloud. Under the bludgeonings of chance, My head is bloody, but unbowed. Beyond this place of wrath and tears, Looms but the Horror of the shade. And yet the menace of the years, Finds and shall find me unafraid. It matters not how strait the gate, How charged with punishments the scroll. I am the master of my fate, I am the captain of my soul.',
            'qans'  :   '12'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/13/', methods=['GET', 'POST'])
def q13():
    dict = {
            'qnum'  :   '13',
            'qtext' :   'Submit a list containing all the IP addresses in the text returned by game.data(13)',
            'qdata' :   '167.99.130.197 - - [05/Feb/2022:15:38:14 +0530] "GET / HTTP/1.1" 404 197 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) Project-Resonance (http://project-resonance.com/) (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36"\n45.146.165.37 - - [05/Feb/2022:15:39:32 +0530] "POST /mifs/.;/services/LogService HTTP/1.1" 404 10573 "https://172.105.56.162:443" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"\n37.228.136.74 - - [05/Feb/2022:15:39:44 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n192.241.212.70 - - [05/Feb/2022:15:42:33 +0530] "GET / HTTP/1.1" 301 5 "-" "Mozilla/5.0 zgrab/0.x"\n62.233.120.26 - - [05/Feb/2022:15:42:50 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n125.227.127.195 - - [05/Feb/2022:15:45:49 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n103.171.180.203 - - [05/Feb/2022:15:49:03 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n45.32.100.183 - - [05/Feb/2022:15:51:38 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n208.109.68.114 - - [05/Feb/2022:15:52:45 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n95.111.250.205 - - [05/Feb/2022:15:56:07 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n208.109.26.136 - - [05/Feb/2022:15:59:28 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n167.99.84.255 - - [05/Feb/2022:16:02:54 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n185.191.171.37 - - [05/Feb/2022:16:04:44 +0530] "GET /maintenance/ HTTP/1.1" 200 12915 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"\n184.168.102.202 - - [05/Feb/2022:16:06:08 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n66.249.66.84 - - [05/Feb/2022:16:06:21 +0530] "GET / HTTP/1.1" 200 17200 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"\n66.249.66.82 - - [05/Feb/2022:16:06:24 +0530] "GET /wp-content/plugins/tco-email-forms/email-integration/js/site/main.js HTTP/1.1" 200 4635 "https://exoton.org/" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"\n185.61.154.35 - - [05/Feb/2022:16:09:12 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n173.201.184.177 - - [05/Feb/2022:16:12:50 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n116.255.173.135 - - [05/Feb/2022:16:16:27 +0530] "POST /xmlrpc.php HTTP/1.1" 200 413 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"\n',
            'qans'  :   "['167.99.130.197', '45.146.165.37', '172.105.56.162', '37.228.136.74', '192.241.212.70', '62.233.120.26', '125.227.127.195', '103.171.180.203', '45.32.100.183', '208.109.68.114', '95.111.250.205', '208.109.26.136', '167.99.84.255', '185.191.171.37', '184.168.102.202', '66.249.66.84', '66.249.66.82', '185.61.154.35', '173.201.184.177', '116.255.173.135']"
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

