from flask import Blueprint, jsonify, request

question_bp = Blueprint('question', __name__, url_prefix='/question')

@question_bp.route('/1/', methods=['GET', 'POST'])
def q1():
    dict = {
            'qnum' :    '1',
            'qtext':    'What is the sum of game.data(1) and 3154?',
            'qdata':    5927,
            'qans' :    '9081'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qtext': dict['qtext'], 'qnum': dict['qnum'], 'qdata': dict['qdata']})

@question_bp.route('/2/', methods=['GET', 'POST'])
def q2():
    dict = {
            'qnum'  :   '2',
            'qtext' :   'Which element in the list returned by game.data(2) is at index position 37?',
            'qdata' :   [386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 958, 743, 527],
            'qans'  :   '892'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/3/', methods=['GET', 'POST'])
def q3():
    dict = {
            'qnum'  :   '3',
            'qtext' :   'Return a string that contains the characters starting at index 10 and going upto but not including the character at index 25 in the string generated by game.data(3) function.  ',
            'qdata' :   'Yes! Yes! Bombay is berry berry nice this time of the year.',
            'qans'  :   'Bombay is berry'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})

@question_bp.route('/4/', methods=['GET', 'POST'])
def q4():
    dict = {
            'qnum'  :   '4',
            'qtext' :   'Reverse the string generated by game.data(4) function.  ',
            'qdata' :   'Yes! Yes! Bombay is berry berry nice this time of the year.',
            'qans'  :   '.raey eht fo emit siht ecin yrreb yrreb si yabmoB !seY !seY'
            }
    if request.method == 'POST':
        ans = request.get_json()['ans']
        if ans == dict['qans']:
            return jsonify({'check':'Correct Answer'})
        else:
            return jsonify({'check':'Incorrect Answer. Please try again'})
    else:
        return jsonify({'qnum': dict['qnum'], 'qtext': dict['qtext'], 'qdata': dict['qdata']})